#!/usr/bin/env python3
# Compares StaticInst flags and op classes of the instructions generated by
# Protea with the ones of the native gem5 RISC-V ISA description.
#
# The native reference is produced by running the gem5 ISA parser on
# src/arch/riscv/isa/main.isa: the generated constructors contain every flag,
# including the ones the parser infers from operands (IsInteger, IsLoad, ...).
# The Protea side is produced by running the generator from this repository.
#
# Flags set conditionally on decoded register numbers (IsCall/IsReturn) are
# compared by name and, for Protea, evaluated against the RISC-V return
# address stack hints for every rd/rs1. Native jal and jalr share one
# constructor template whose IsReturn code is reachable only for jalr, so
# IsReturn is expected only for indirect jumps (as in the RISC-V spec).
#
# Usage: gem5/tests/check_flags.py <gem5 repo root> [--ir <lira.yaml>]
# Exits with 1 if any instruction differs.

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

PROTEA_GEM5 = Path(__file__).resolve().parent.parent
LINK_REGS = (1, 5)


def run_native_parser(gem5: Path, out: Path) -> Path:
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(
        str(gem5 / d) for d in ("src/arch", "build_tools", "ext/ply"))
    code = ("import isa_parser, sys; "
            "isa_parser.ISAParser(sys.argv[1]).parse_isa_desc(sys.argv[2])")
    subprocess.run([sys.executable, "-c", code, str(out),
                    str(gem5 / "src/arch/riscv/isa/main.isa")],
                   env=env, check=True, stdout=subprocess.DEVNULL)
    return out / "decoder-ns.cc.inc"


def run_protea_generator(gem5: Path, ir: Path, out: Path) -> Path:
    python = gem5 / "build/protea-venv/bin/python"
    subprocess.run([str(python), str(PROTEA_GEM5 / "main.py"), "--ir-path", str(ir)],
                   cwd=out, check=True)
    return out / "src/arch/riscv/isa/decoder_protea.isa"


def parse_native(path: Path) -> dict:
    """mnemonic -> (op_class, static flags, conditional flags)."""
    text = path.read_text()
    ctor = re.compile(
        r'^\s*(\w+)::\1\(ExtMachInst machInst\)\s*:?\s*:?\s*'
        r'[\w<>:]+\("([\w.]+)", machInst, (\w+)\)', re.M)
    matches = list(ctor.finditer(text))
    insts = {}
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[m.end():end]
        # Flags from the instruction definition are emitted with a tab at the
        # beginning of the line, the ones in template code are indented
        # with spaces and are conditional.
        static = set(re.findall(r'^\tflags\[(\w+)\] = true;', body, re.M))
        cond = set(re.findall(r'^ +.*flags\[(\w+)\] = true;', body, re.M))
        insts.setdefault(m.group(2), (m.group(3), static, cond))
    return insts


def parse_protea(path: Path) -> dict:
    """mnemonic -> (op_class, static flags, {conditional flag: condition})."""
    text = path.read_text()
    insts = {}
    for block in re.split(r'\n(?=\d+: [A-Z_]+\()', text):
        m = re.match(r'\d+: ([A-Z_]+)\(', block)
        if not m:
            continue
        op_class = re.search(r'op_class = \{\{ (\S+) \}\}', block).group(1)
        defs = block[block.index("memb_defs"):block.index("meth_decls")]
        static = set(re.findall(r'^flags\[(\w+)\] = true;', defs, re.M))
        cond = {flag: expr for expr, flag in
                re.findall(r'^if \((.*)\) flags\[(\w+)\] = true;', defs, re.M)}
        insts[m.group(1).lower()] = (op_class, static, cond)
    return insts


def c_to_python(expr: str) -> str:
    expr = expr.replace("!=", " NE ").replace("||", " or ").replace("&&", " and ")
    return expr.replace("!", " not ").replace(" NE ", " != ")


def ras_reference(flag: str, rd: int, rs1: int) -> bool:
    rd_link, rs1_link = rd in LINK_REGS, rs1 in LINK_REGS
    if flag == "IsCall":
        return rd_link
    return rs1_link and (not rd_link or rs1 != rd)


def check_condition(flag: str, expr: str) -> list:
    errors = []
    code = compile(c_to_python(expr), expr, "eval")
    for rd in range(32):
        for rs1 in range(32):
            got = bool(eval(code, {}, {"rd": rd, "rs1": rs1}))
            if got != ras_reference(flag, rd, rs1):
                errors.append(f"{flag} for rd={rd} rs1={rs1}: got {got}")
    return errors[:3]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("gem5", type=Path, help="gem5 repository root")
    ap.add_argument("--ir", type=Path,
                    help="LIRA IR (default: <gem5>/ext/protea/Protea/build/"
                         "Default-Release/lib/lira.yaml)")
    args = ap.parse_args()
    gem5 = args.gem5.resolve()
    ir = (args.ir or gem5 / "ext/protea/Protea/build/Default-Release/lib/lira.yaml").resolve()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        (tmp / "native").mkdir()
        native = parse_native(run_native_parser(gem5, tmp / "native"))
        protea = parse_protea(run_protea_generator(gem5, ir, tmp))

    failed = 0
    for name, (op_class, static, cond) in sorted(protea.items()):
        if name not in native:
            print(f"{name:8} SKIP: no such instruction in native gem5")
            continue
        ref_op_class, ref_static, ref_cond = native[name]
        errors = []
        if op_class != ref_op_class:
            errors.append(f"op_class {op_class}, expected {ref_op_class}")
        if static - ref_static:
            errors.append(f"extra flags {sorted(static - ref_static)}")
        if ref_static - static:
            errors.append(f"missing flags {sorted(ref_static - static)}")
        exp_cond = set(ref_cond)
        if "IsIndirectControl" not in ref_static:
            exp_cond.discard("IsReturn")
        if set(cond) != exp_cond:
            errors.append(f"conditional flags {sorted(cond)}, expected {sorted(exp_cond)}")
        for flag, expr in cond.items():
            if flag in ("IsCall", "IsReturn"):
                errors += check_condition(flag, expr)
        if errors:
            failed += 1
            print(f"{name:8} FAIL: " + "; ".join(errors))
        else:
            print(f"{name:8} ok   {op_class:10} {' '.join(sorted(static | set(cond)))}")

    print()
    if failed:
        print(f"Summary: {failed} of {len(protea)} instructions differ from native gem5")
        return 1
    print(f"Summary: flags and op classes of all {len(protea)} instructions "
          "match native gem5")
    return 0


if __name__ == "__main__":
    sys.exit(main())
