# frozen_string_literal: true

require_relative 'lexer'
require_relative 'parser'

module Plod
  module Pld
    # Translates a parsed .pld description into Ruby DSL source that the
    # Plod frontend understands. The output is deterministic and preserves
    # the paragraph structure (blank lines) of the .pld source.
    #
    #   Mapping rules:
    #   - PascalCase type/decl names are kept; enum references get a
    #     lowercase-first receiver: `InterruptIds.Rx` -> `interruptIds.Rx`.
    #   - Register props and return types map to capitalized Ruby kwargs:
    #     `size(0x1)` -> `Size: 0x1`, `type(ro)` -> `Type: :ro`,
    #     `b8 read()` -> `Method(:read, Ret: B8())`.
    #   - Assignments (including compound ones) lower to `name[] = expr`,
    #     desugaring `x |= y` to `x[] = x | y`; `self` becomes `this`.
    #   - `&x` lowers to `GetPtr(x)`, `static_cast<T>(e)` to `Cast(T(), e)`.
    #   - `if/else if/else` lowers to sibling `If` / `Elseif` / `Else` DSL
    #     statements; integer literals keep their original spelling (0x0A).
    class Translator
      PREC = {
        '||' => 5, '&&' => 7, '|' => 10, '^' => 15, '&' => 20,
        '==' => 25, '!=' => 25, '<' => 30, '<=' => 30, '>' => 30, '>=' => 30,
        '<<' => 35, '>>' => 35, '+' => 40, '-' => 40, '*' => 50, '/' => 50, '%' => 50
      }.freeze

      def self.translate(source, path = '(pld)')
        new(Parser.parse(source, path)).translate
      end

      def self.translate_file(path)
        translate(File.read(path), path)
      end

      def initialize(ast)
        @ast = ast
        @enum_names = collect_enum_names
        @out = +''
        @indent = 0
      end

      def translate
        emit_line('# frozen_string_literal: true')
        emit_line('')
        emit_line('# Generated by `plod translate` — do not edit; edit the .pld source instead.')
        @ast.decls.each_with_index do |decl, idx|
          emit_line('') if idx.positive?
          translate_decl(decl)
        end
        @out
      end

      private

      def collect_enum_names
        @ast.decls.filter_map do |decl|
          next unless decl.is_a?(Parser::DeviceDecl)

          decl.decls.filter_map { |d| d.name if d.is_a?(Parser::EnumDecl) }
        end.flatten
      end

      # -- emission helpers ------------------------------------------------------
      def emit_line(text = '')
        @out << ('  ' * @indent) << text << "\n"
      end

      def blank_line(item)
        @out << "\n" if item.respond_to?(:blank) && item.blank
      end

      def with_block(header)
        emit_line("#{header} {")
        @indent += 1
        yield
        @indent -= 1
        emit_line('}')
      end

      def with_block_body(header, body)
        return emit_line("#{header} {}") if body.nil? || body.empty?

        emit_line("#{header} {")
        @indent += 1
        body.each { |stmt| translate_stmt(stmt) }
        @indent -= 1
        emit_line('}')
      end

      # -- declarations ------------------------------------------------------------
      def translate_decl(decl)
        case decl
        when Parser::StructDecl then translate_struct(decl)
        when Parser::ObjectDecl then translate_object(decl)
        when Parser::FunctionDecl then translate_function(decl)
        when Parser::DeviceDecl then translate_device(decl)
        else raise Plod::Error.new("cannot translate #{decl.class}", nil)
        end
      end

      def translate_struct(decl)
        kind = decl.abstract ? 'AbstractStruct' : 'Struct'
        return emit_line("#{kind}(:#{decl.name}) {}") if decl.items.empty?

        with_block("#{kind}(:#{decl.name})") do
          decl.items.each { |m| translate_struct_member(m) }
        end
      end

      def translate_struct_member(member)
        blank_line(member)
        case member
        when Parser::MethodDecl
          if member.body
            with_block_body(method_call('Method', member.name, member.args, member.ret), member.body)
          else
            emit_line(method_call('Method', member.name, member.args, member.ret))
          end
        when Parser::FieldDecl
          emit_line("Field(:#{member.name}, #{type_expr(member.type)})")
        end
      end

      def translate_object(decl)
        emit_line("AbstractObject(:#{decl.name}, #{type_expr(decl.type)})")
      end

      def translate_function(decl)
        emit_line(method_call('AbstractMethod', decl.name, decl.args, decl.ret))
      end

      def translate_device(decl)
        with_block("Device(:#{decl.name})") do
          decl.decls.each { |d| translate_device_decl(d) }
        end
      end

      def translate_device_decl(decl)
        blank_line(decl)
        case decl
        when Parser::EnumDecl then translate_enum(decl)
        when Parser::ConstDecl then translate_const(decl)
        when Parser::MethodDecl then translate_device_method(decl)
        when Parser::RegisterDecl then translate_register(decl)
        when Parser::FieldDecl then translate_field(decl)
        end
      end

      def translate_enum(decl)
        with_block("Enum(:#{ruby_enum_name(decl.name)})") do
          decl.pairs.each { |key, int| emit_line("#{key}(#{int[:raw]})") }
        end
      end

      def translate_const(decl)
        emit_line("Const(:#{decl.name}, #{type_expr(decl.type)}, #{decl.value[:raw]})")
      end

      def translate_device_method(decl)
        return emit_line(method_call('AbstractMethod', decl.name, decl.args, decl.ret)) if decl.abstract

        with_block_body(method_call('Method', decl.name, decl.args, decl.ret), decl.body)
      end

      def translate_register(decl)
        kwargs = decl.props.map { |name, arg| register_kwarg(name, arg) }.join(', ')
        header = kwargs.empty? ? "Register(:#{decl.name})" : "Register(:#{decl.name}, #{kwargs})"
        return emit_line("#{header} {}") if decl.items.empty?

        with_block(header) do
          decl.items.each { |item| translate_register_item(item) }
        end
      end

      def register_kwarg(name, arg)
        value = arg.is_a?(Hash) ? arg[:raw] : arg
        name == 'type' ? "Type: :#{value}" : "#{name.capitalize}: #{value}"
      end

      def translate_register_item(item)
        blank_line(item)
        case item
        when Parser::EnableIf
          emit_line("EnableIf { #{expr(item.expr)} }")
        when Parser::RegFieldDecl
          range = item.lo == item.hi ? item.lo : "[#{item.lo}, #{item.hi}]"
          emit_line("Field :#{item.name}, #{range}")
        when Parser::MethodDecl
          with_block_body(method_call('Method', item.name, item.args, item.ret), item.body)
        end
      end

      def translate_field(decl)
        return emit_line("AbstractField(:#{decl.name}, #{type_expr(decl.type)})") if decl.abstract
        return emit_line("Field(:#{decl.name}, #{type_expr(decl.type)}, #{init_expr(decl.init)})") if decl.init

        emit_line("Field(:#{decl.name}, #{type_expr(decl.type)})")
      end

      # -- signatures -----------------------------------------------------------------
      def method_call(kind, name, args, ret)
        kwargs = args.map { |p| "#{p.name}: #{type_expr(p.type)}" }
        kwargs << "Ret: #{type_expr(ret)}" if ret && ret.name != 'void'
        kwargs.empty? ? "#{kind}(:#{name})" : "#{kind}(:#{name}, #{kwargs.join(', ')})"
      end

      def type_expr(type)
        return '()' if type.nil? || type.name == 'void'

        base =
          case type.name
          when 'bool' then 'Bool()'
          when 'int' then 'Int()'
          when 'string' then 'String()'
          when 'auto' then 'Auto()'
          when /\Ab(\d+)\z/ then "B#{Regexp.last_match(1)}()"
          else "#{type.name}()"
          end
        type.pointer.to_i.times { base = "Ptr(#{base})" }
        base = "Array(#{base}, #{type.array_size})" if type.array_size
        base
      end

      def ruby_enum_name(name)
        name[0].downcase + name[1..]
      end

      # -- statements --------------------------------------------------------------------
      # -- expressions ----------------------------------------------------------------------

      def translate_stmt(stmt)
        blank_line(stmt)
        case stmt
        when Parser::IfStmt then translate_if(stmt)
        when Parser::ReturnStmt then translate_return(stmt)
        when Parser::VarStmt then translate_var(stmt)
        when Parser::AssignStmt then translate_assign(stmt)
        when Parser::ExprStmt then emit_line(expr(stmt.expr))
        end
      end

      def translate_if(stmt)
        with_block("If(#{expr(stmt.cond)})") { stmt.then_body.each { |s| translate_stmt(s) } }
        stmt.elsif_list.each do |cond, body|
          with_block("Elseif(#{expr(cond)})") { body.each { |s| translate_stmt(s) } }
        end
        return if stmt.else_body.nil?

        with_block('Else') { stmt.else_body.each { |s| translate_stmt(s) } }
      end

      def translate_return(stmt)
        emit_line(stmt.expr ? "Return #{expr(stmt.expr)}" : 'Return()')
      end

      def translate_var(stmt)
        if stmt.init
          emit_line("Let :#{stmt.name}, #{type_expr(stmt.type)}, #{expr(stmt.init)}")
        else
          emit_line("Var :#{stmt.name}, #{type_expr(stmt.type)}")
        end
      end

      def translate_assign(stmt)
        lhs = stmt.target.is_a?(Parser::Ident) && stmt.target.name == 'self' ? 'this' : expr(stmt.target)
        value = expr(stmt.value)
        rhs = stmt.op == '=' ? value : "#{lhs} #{stmt.op[0]} #{value}"
        emit_line("#{lhs}[] = #{rhs}")
      end

      # -- expressions ----------------------------------------------------------------------

      def expr(node)
        case node
        when Parser::IntLit then node.token[:raw]
        when Parser::StrLit then string_lit(node.token[:value])
        when Parser::Ident then node.name == 'self' ? 'this' : node.name
        when Parser::BinOp then binop_expr(node)
        when Parser::UnOp then "#{node.op}#{paren_operand(node.operand, 60)}"
        when Parser::Member then member_expr(node)
        when Parser::Call then call_expr(node)
        when Parser::StaticCast then "Cast(#{type_expr(node.type)}, #{expr(node.expr)})"
        when Parser::AddrOf then "GetPtr(#{expr(node.expr)})"
        when Parser::Lambda then lambda_expr(node)
        else raise Plod::Error.new("cannot translate expression #{node.class}", nil)
        end
      end

      def binop_expr(node)
        prec = PREC[node.op]
        "#{paren_operand(node.lhs, prec)} #{ruby_op(node.op)} #{paren_operand(node.rhs, prec + 1)}"
      end

      def paren_operand(node, min_prec)
        text = expr(node)
        needs = node.is_a?(Parser::BinOp) && PREC[node.op] < min_prec
        needs ? "(#{text})" : text
      end

      def ruby_op(op)
        case op
        when '&&' then '&'
        when '||' then '|'
        else op
        end
      end

      def member_expr(node)
        recv = if node.recv.is_a?(Parser::Ident) && @enum_names.include?(node.recv.name)
                 ruby_enum_name(node.recv.name)
               else
                 expr(node.recv)
               end
        "#{recv}.#{node.name}"
      end

      def call_expr(node)
        target = expr(node.target)
        return target if node.args.empty?

        "#{target}(#{node.args.map { |a| expr(a) }.join(', ')})"
      end

      def lambda_expr(node)
        body = node.body.map { |stmt| expr(stmt.is_a?(Parser::ExprStmt) ? stmt.expr : stmt) }
        "Lambda { #{body.join('; ')} }"
      end

      def string_lit(value)
        value.include?("'") || value.include?('\\') ? value.inspect : "'#{value}'"
      end

      # Field initializer: `T name = Ctor(args...)` lowers to the DSL's
      # Field(name, T(), args...) — the constructor name itself is dropped.
      def init_expr(node)
        return expr(node) unless node.is_a?(Parser::Call)

        args = node.args.map { |a| expr(a) }
        args.empty? ? nil : args.join(', ')
      end
    end
  end
end
